function h = plotSegment(segments)
h = figure('Name','Target Segment Object Display');
hold on;
for i = 1:length(segments.facets)
    if isa(segments.facets(i),'clRectangle')
        vtri = [segments.facets(i).base,...
            segments.facets(i).base+segments.facets(i).edge1,...
            segments.facets(i).base+segments.facets(i).edge1+...
            segments.facets(i).edge2,...
            segments.facets(i).base+segments.facets(i).edge2].';
        f = [1 2 3 4];
        patch('Faces',f,'Vertices',vtri,'FaceColor',       [0.8 0.8 1.0], ...
             'EdgeColor',       'black',        ...
             'FaceLighting',    'gouraud',     ...
             'FaceAlpha', 0.1);
    else
        vtri = [segments.facets(i).base,...
            segments.facets(i).base+segments.facets(i).edge1,...
            segments.facets(i).base+segments.facets(i).edge2].';
        f = [1 2 3];
        patch('Faces',f,'Vertices',vtri,'FaceColor',       [0.8 0.8 1.0], ...
             'EdgeColor',       'black',        ...
             'FaceLighting',    'gouraud',     ...
             'FaceAlpha', 0.1);
    end
end
plot2tikz('3ucubesat_faceted',0.6);
view([120 20]);
xlabel('x');
ylabel('y');
zlabel('z');
% set(gca,'xticklabel',[])
% set(gca,'yticklabel',[])
% set(gca,'zticklabel',[])
axis equal;
grid;
end

