function h = plotSegmentWithPointCloud(cmptarget,ptcl)
h = figure('Name','Target Segment Object Display');
pcshow(ptcl.', 'MarkerSize', 20);
hold on;
for i = 1:length(cmptarget.segments.facets)
    if isa(cmptarget.segments.facets(i),'clRectangle')
        vtri = [cmptarget.segments.facets(i).base, ...
            cmptarget.segments.facets(i).base+cmptarget.segments.facets(i).edge1, ...
            cmptarget.segments.facets(i).base+cmptarget.segments.facets(i).edge1+...
            cmptarget.segments.facets(i).edge2, ...
            cmptarget.segments.facets(i).base+cmptarget.segments.facets(i).edge2].';
        f = [1 2 3 4];
        patch('Faces',f,'Vertices',vtri,'FaceColor',       [0.8 0.8 1.0], ...
             'EdgeColor',       'black',        ...
             'FaceLighting',    'gouraud',     ...
             'FaceAlpha', 0.1);
    else
        vtri = [cmptarget.segments.facets(i).base,...
            cmptarget.segments.facets(i).base+cmptarget.segments.facets(i).edge1,...
            cmptarget.segments.facets(i).base+cmptarget.segments.facets(i).edge2].';
        f = [1 2 3];
        patch('Faces',f,'Vertices',vtri,'FaceColor',       [0.8 0.8 1.0], ...
             'EdgeColor',       'none',        ...
             'FaceLighting',    'gouraud',     ...
             'FaceAlpha', 0.1);
    end
end
view([120 20]);
xlabel('x');
ylabel('y');
zlabel('z');
% set(gca,'xticklabel',[])
% set(gca,'yticklabel',[])
% set(gca,'zticklabel',[])
axis equal;
grid;
end

